/*
Created on Tue Mar 21 22:54:08 2023

@author: Tom Zhao

For learning and training purpose: all team member in our P3 project.
*/

#Insert data into table 'department'

INSERT INTO p3project.Departments(department_id,department) VALUES (1, 'frozen');
INSERT INTO p3project.Departments(department_id,department) VALUES (2, 'other');
INSERT INTO p3project.Departments(department_id,department) VALUES (3, 'bakery');
INSERT INTO p3project.Departments(department_id,department) VALUES (4, 'produce');
INSERT INTO p3project.Departments(department_id,department) VALUES (5, 'alcohol');
INSERT INTO p3project.Departments(department_id,department) VALUES (6, 'international');
INSERT INTO p3project.Departments(department_id,department) VALUES (7, 'beverages');
INSERT INTO p3project.Departments(department_id,department) VALUES (8, 'pets');
INSERT INTO p3project.Departments(department_id,department) VALUES (9, 'dry goods pasta');
INSERT INTO p3project.Departments(department_id,department) VALUES (10, 'bulk');
INSERT INTO p3project.Departments(department_id,department) VALUES (11, 'personal care');
INSERT INTO p3project.Departments(department_id,department) VALUES (12, 'meat seafood');
INSERT INTO p3project.Departments(department_id,department) VALUES (13, 'pantry');
INSERT INTO p3project.Departments(department_id,department) VALUES (14, 'breakfast');
INSERT INTO p3project.Departments(department_id,department) VALUES (15, 'canned goods');
INSERT INTO p3project.Departments(department_id,department) VALUES (16, 'dairy eggs');
INSERT INTO p3project.Departments(department_id,department) VALUES (17, 'household');
INSERT INTO p3project.Departments(department_id,department) VALUES (18, 'babies');
INSERT INTO p3project.Departments(department_id,department) VALUES (19, 'snacks');
INSERT INTO p3project.Departments(department_id,department) VALUES (20, 'deli');
INSERT INTO p3project.Departments(department_id,department) VALUES (21, 'missing');

#Insert data into table 'aisles'

INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (1, 'prepared soups salads');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (2, 'specialty cheeses');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (3, 'energy granola bars');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (4, 'instant foods');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (5, 'marinades meat preparation');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (6, 'other');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (7, 'packaged meat');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (8, 'bakery desserts');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (9, 'pasta sauce');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (10, 'kitchen supplies');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (11, 'cold flu allergy');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (12, 'fresh pasta');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (13, 'prepared meals');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (14, 'tofu meat alternatives');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (15, 'packaged seafood');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (16, 'fresh herbs');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (17, 'baking ingredients');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (18, 'bulk dried fruits vegetables');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (19, 'oils vinegars');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (20, 'oral hygiene');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (21, 'packaged cheese');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (22, 'hair care');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (23, 'popcorn jerky');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (24, 'fresh fruits');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (25, 'soap');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (26, 'coffee');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (27, 'beers coolers');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (28, 'red wines');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (29, 'honeys syrups nectars');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (30, 'latino foods');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (31, 'refrigerated');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (32, 'packaged produce');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (33, 'kosher foods');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (34, 'frozen meat seafood');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (35, 'poultry counter');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (36, 'butter');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (37, 'ice cream ice');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (38, 'frozen meals');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (39, 'seafood counter');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (40, 'dog food care');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (41, 'cat food care');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (42, 'frozen vegan vegetarian');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (43, 'buns rolls');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (44, 'eye ear care');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (45, 'candy chocolate');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (46, 'mint gum');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (47, 'vitamins supplements');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (48, 'breakfast bars pastries');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (49, 'packaged poultry');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (50, 'fruit vegetable snacks');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (51, 'preserved dips spreads');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (52, 'frozen breakfast');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (53, 'cream');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (54, 'paper goods');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (55, 'shave needs');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (56, 'diapers wipes');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (57, 'granola');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (58, 'frozen breads doughs');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (59, 'canned meals beans');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (60, 'trash bags liners');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (61, 'cookies cakes');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (62, 'white wines');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (63, 'grains rice dried goods');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (64, 'energy sports drinks');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (65, 'protein meal replacements');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (66, 'asian foods');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (67, 'fresh dips tapenades');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (68, 'bulk grains rice dried goods');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (69, 'soup broth bouillon');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (70, 'digestion');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (71, 'refrigerated pudding desserts');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (72, 'condiments');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (73, 'facial care');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (74, 'dish detergents');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (75, 'laundry');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (76, 'indian foods');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (77, 'soft drinks');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (78, 'crackers');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (79, 'frozen pizza');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (80, 'deodorants');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (81, 'canned jarred vegetables');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (82, 'baby accessories');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (83, 'fresh vegetables');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (84, 'milk');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (85, 'food storage');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (86, 'eggs');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (87, 'more household');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (88, 'spreads');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (89, 'salad dressing toppings');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (90, 'cocoa drink mixes');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (91, 'soy lactosefree');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (92, 'baby food formula');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (93, 'breakfast bakery');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (94, 'tea');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (95, 'canned meat seafood');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (96, 'lunch meat');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (97, 'baking supplies decor');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (98, 'juice nectars');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (99, 'canned fruit applesauce');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (100, 'missing');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (101, 'air fresheners candles');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (102, 'baby bath body care');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (103, 'ice cream toppings');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (104, 'spices seasonings');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (105, 'doughs gelatins bake mixes');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (106, 'hot dogs bacon sausage');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (107, 'chips pretzels');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (108, 'other creams cheeses');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (109, 'skin care');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (110, 'pickled goods olives');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (111, 'plates bowls cups flatware');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (112, 'bread');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (113, 'frozen juice');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (114, 'cleaning products');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (115, 'water seltzer sparkling water');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (116, 'frozen produce');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (117, 'nuts seeds dried fruit');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (118, 'first aid');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (119, 'frozen dessert');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (120, 'yogurt');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (121, 'cereal');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (122, 'meat counter');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (123, 'packaged vegetables fruits');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (124, 'spirits');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (125, 'trail mix snack mix');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (126, 'feminine care');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (127, 'body lotions soap');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (128, 'tortillas flat bread');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (129, 'frozen appetizers sides');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (130, 'hot cereal pancake mixes');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (131, 'dry pasta');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (132, 'beauty');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (133, 'muscles joints pain relief');
INSERT INTO p3project.Aisles(aisle_id,aisle) VALUES (134, 'specialty wines champagnes');